services:
     openspeedtest:
              image: openspeedtest/latest
              ports:
                - "9000:3000"
              container_name: openspeedtest
              restart: unless-stopped
